version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm install
      - cd ..
      - echo "Installing backend dependencies"
      - cd backend
      - npm install  # or pip install -r requirements.txt
      - cd ..
  build:
    commands:
      - echo "Building frontend"
      - cd frontend
      - npm run build
      - cd ..
      # You can also compile or prepare backend here if needed
artifacts:
  files:
    - frontend/build/**/*
    - backend/**/*  # Adjust to include only what backend needs