version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed.
      - ls -l artifacts/

artifacts:
  files:
    - 'artifacts/**/*'
  base-directory: dist
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'